In [1]:
import numpy as np
import pandas as pd 
import requests
import pandas as pd
from path import Path

In [2]:
#import csv and compile into dataframes
btc_df = pd.read_csv(
    Path("Resources/historical_data_bitcoin.csv"))
eth_df = pd.read_csv(
    Path("Resources/historical_data_ethereum.csv"))
ada_df = pd.read_csv(
    Path("Resources/historical_data_cardano.csv"))

In [3]:
btc_df.head()

,Date,Price (Close),Marketcap Dominance,Volatility,Active Addresses Count,Addresses with balance greater than $100K,Average Transaction Fees
0,2022-11-12,16902.437540,NaN,0.768576,NaN,NaN,NaN
1,2022-11-11,17027.298053,37.397954,0.783906,964454.0,211623.0,1.293462
2,2022-11-10,17556.011672,37.564432,0.748417,1056871.0,214833.0,1.434724
3,2022-11-09,15884.702615,37.907971,0.613921,1076579.0,200223.0,1.380111
4,2022-11-08,18547.764683,37.795770,0.491753,1051006.0,220906.0,1.370737

In [4]:
eth_df.head()

,Date,Price (Close),Marketcap Dominance,Volatility,Active Addresses Count,Addresses with balance greater than $100K,Average Transaction Fees
0,2022-11-12,1272.529120,NaN,1.148067,NaN,NaN,NaN
1,2022-11-11,1285.965877,17.589981,1.148677,508831.0,58957.0,3.597904
2,2022-11-10,1295.875437,16.626569,1.195470,494969.0,59175.0,5.325952
3,2022-11-09,1103.946357,17.382468,0.925252,510135.0,51909.0,6.025663
4,2022-11-08,1334.736734,18.347879,0.800867,478829.0,59703.0,6.821070

In [5]:
ada_df.head()

,Date,Price (Close),Marketcap Dominance,Volatility,Active Addresses Count,Addresses with balance greater than $100K,Average Transaction Fees
0,2022-11-12,0.344099,NaN,1.044591,NaN,NaN,NaN
1,2022-02-19,NaN,NaN,0.791088,177722.0,23817.0,0.369003
2,2022-02-20,NaN,NaN,0.790735,230015.0,22134.0,0.307771
3,2021-08-28,2.849475,5.106208,1.268181,138728.0,60266.0,0.622318
4,2021-08-30,2.736199,4.986402,1.279403,136707.0,59188.0,0.582567

In [6]:
#normalize dataframes
btc_df = btc_df.set_index("Date").dropna()

eth_df = eth_df.set_index("Date").dropna()

ada_df = ada_df.set_index("Date").dropna()

In [7]:
#set data frames to pct change and drop null values
btc_pct = btc_df.pct_change().dropna() 
eth_pct = eth_df.pct_change().dropna()
ada_pct = ada_df.pct_change().dropna()

In [8]:
btc_pct.head()

,Price (Close),Marketcap Dominance,Volatility,Active Addresses Count,Addresses with balance greater than $100K,Average Transaction Fees
Date,,,,,,
2022-11-10,0.031051,0.004452,-0.045272,0.095823,0.015168,0.109212
2022-11-09,-0.095199,0.009145,-0.179707,0.018647,-0.068006,-0.038065
2022-11-08,0.167649,-0.002960,-0.198997,-0.023754,0.103300,-0.006792
2022-11-07,0.110316,0.012176,-0.371137,-0.124407,0.150919,-0.097120
2022-11-06,0.015277,-0.009934,0.009013,-0.118093,0.006848,-0.007845

In [9]:
eth_pct.head()

,Price (Close),Marketcap Dominance,Volatility,Active Addresses Count,Addresses with balance greater than $100K,Average Transaction Fees
Date,,,,,,
2022-11-10,0.007706,-0.054770,0.040736,-0.027243,0.003698,0.480293
2022-11-09,-0.148108,0.045463,-0.226035,0.030640,-0.122788,0.131378
2022-11-08,0.209059,0.055539,-0.134434,-0.061368,0.150147,0.132003
2022-11-07,0.175097,-0.003355,-0.267214,0.044740,0.132791,-0.528275
2022-11-06,0.000004,0.008468,-0.020709,-0.035576,-0.000311,-0.196641

In [10]:
ada_pct.head()

,Price (Close),Marketcap Dominance,Volatility,Active Addresses Count,Addresses with balance greater than $100K,Average Transaction Fees
Date,,,,,,
2021-08-30,-0.039753,-0.023463,0.008849,-0.014568,-0.017887,-0.063875
2021-08-29,0.042845,-0.004563,-0.011537,0.097764,0.029212,0.166902
2021-08-31,-0.029262,-0.015636,0.017659,-0.194913,-0.047015,-0.138345
2021-09-01,0.036499,-0.006412,-0.002596,0.046912,0.023702,0.003202
2021-09-02,0.031660,-0.019308,-0.001583,0.189155,0.021908,0.037097

In [19]:
btc_price = btc_df["Price (Close)"]
eth_price = eth_df["Price (Close)"]
ada_price = ada_df["Price (Close)"]
price_comp = pd.concat([btc_price,eth_price,ada_price],axis=1)
price_comp.head()

            Price (Close)  Price (Close)  Price (Close)
Date
2022-11-11   17027.298053    1285.965877       0.354677
2022-11-10   17556.011672    1295.875437       0.367726
2022-11-09   15884.702615    1103.946357       0.317355
2022-11-08   18547.764683    1334.736734       0.372214
2022-11-07   20593.887999    1568.444912       0.404113

In [20]:
price_comp = pd.concat([btc_price,eth_price,ada_price],axis=1)
price_comp.head()

            Price (Close)  Price (Close)  Price (Close)
Date
2022-11-11   17027.298053    1285.965877       0.354677
2022-11-10   17556.011672    1295.875437       0.367726
2022-11-09   15884.702615    1103.946357       0.317355
2022-11-08   18547.764683    1334.736734       0.372214
2022-11-07   20593.887999    1568.444912       0.404113